### ISSUE TITLE
Roadmap Improvements

### ISSUE THREAD

**Issue by Stryxus** [Star-Aether/Core#35]
- [ ] Download and transcode all RSI images to WebP.
- [ ] Store all transcoded images in Azure Blob Storage.
- [x] Update roadmap data scraping to the RSI API.
- [x] Convert RSI API Json to usable trimmed Json.
- [ ] Store all usable Json in the Mongo Database.
- [x] Create a system which determines if 2 weeks have passed.
- [ ] General roadmap UI refinement.
- [ ] Add ability to change the roadmap data set to something from an earlier date.
- [ ] Add controller to force a roadmap update via MIP.
